### ISSUE TITLE
冰套文字错误

### ISSUE THREAD

**Issue by yllhwa** [wormtql/genshin_artifact#1]
冰套的文字似乎错了，但是我没有刷全套所以也不知道正确顺序，可以留意一下。
感谢作者的开源项目。

**Comment by yllhwa** [comment]
另外似乎缺少弓箭类武器的数据

**Comment by wormtql** [comment]
2.0.0即将上线，可以先去http://39.107.68.17/#/体验一下，但是我还不太会打包优化，所以现在首屏加载非常慢，顺便感谢大佬的issue。

**Comment by yllhwa** [comment]
可以套个cdn，你可以看一下我搭载该项目的速度http://www.dear-leland.site

**Comment by yllhwa** [comment]
我没点前端方向的技能树，只能从内容方面给一点建议啦～

**Comment by wormtql** [comment]
哈哈我恰好没点后端运维啥的技能树，现在前端写差不多了要上生产环境一头雾水
