### ISSUE TITLE
万叶计算精通最大时计算结果比游戏内多80

### ISSUE THREAD

**Issue by WatchKitty** [wormtql/genshin_artifact#108]
对于最佳的生之花计算，选用了精通56而不是61的生之花。
此处计算应为90级万叶自身115+沙杯头187*3+56+68=800（装备为腐殖之剑，无精通加成）而计算器计算后为880
![image](https://user-images.githubusercontent.com/63351588/154727743-c73af891-ee16-4a15-bcec-794adfca0462.png)
![image](https://user-images.githubusercontent.com/63351588/154727865-3bcf8f2e-cc3f-4259-b7d0-9d714da600ea.png)
此处为圣遗物列表json（为了能够上传后缀已改为txt）
[mona.txt](https://github.com/wormtql/genshin_artifact/files/8099056/mona.txt)

**Comment by ainopara** [comment]
额外的 80 精通为乐团两件套的效果吧

**Comment by WatchKitty** [comment]
> 额外的 80 精通为乐团两件套的效果吧

原来套装效果不加在游戏面板上的吗，感谢指正！
