### ISSUE TITLE
刻晴暴击率错误

### ISSUE THREAD

**Issue by WSGsety** [wormtql/genshin_artifact#11]
刻晴在解锁玉衡之贵天赋后，在天街巡游时暴击率提升15%。

**Comment by wormtql** [comment]
这个不会体现在面板上，但在计算”刻晴-天街巡游“目标函数的时候是算入其中的

**Comment by WSGsety** [comment]
页面上元素爆发暴击率上是否应该体现出来？

**Comment by wormtql** [comment]
页面上体现的是持久的暴击率，但刻晴只在Q技能期间才会有加成，所以不会体现在面板上 😄

**Comment by WSGsety** [comment]
明白，理解
