### ISSUE TITLE
大乐团攻击力加成效果不叠加

### ISSUE THREAD

**Issue by sidious-82** [wormtql/genshin_artifact#116]
rt

**Comment by wormtql** [comment]
没太听懂

**Comment by sidious-82** [comment]
buff的时候如果选一个时苍古，一个是终末，计算的时候会加20+20=40%的攻击力。
如果主武器是苍古，buff选终末，也是一样的。

但是实际上只能加20%，因为乐章系列武器的相同效果不叠加。比如加20%攻击力。但是其他不同的效果可以共存，比如加伤和加精通

**Comment by wormtql** [comment]
这没办法，架构原因，只能自己选
