### ISSUE TITLE
神里绫华6命效果不能自动考虑

### ISSUE THREAD

**Issue by sidious-82** [wormtql/genshin_artifact#123]
不知道算不算bug

6命神里在计算时不会自动考虑6命效果，要buff里面单独加一下才行。

**Comment by sidious-82** [comment]
现在有按钮了，但是on/off不改变计算结果，事实上霰部也有类似问题

![image](https://user-images.githubusercontent.com/95687554/160252678-3708774b-95ac-4d80-a022-1f4090ff3811.png)
![image](https://user-images.githubusercontent.com/95687554/160252682-ebcac63c-04b8-4915-a262-7ca0806d9dbf.png)

**Comment by wormtql** [comment]
霰步只会附魔，六命只增加重击伤害

**Comment by sidious-82** [comment]
哦哦o，不好意思。我本来是想问4命的。所以4命效果是建议当buff选进来是吧
