### ISSUE TITLE
计算设置中的过虑圣遗物套装不能保存

### ISSUE THREAD

**Issue by sidious-82** [wormtql/genshin_artifact#126]
![image](https://user-images.githubusercontent.com/95687554/160176312-cb1acba7-e8fd-4228-bae7-c8c752fc61ea.png)

每次刷新之后就没有被选中了

**Comment by wormtql** [comment]
过滤套装设计为不保存，因为圣遗物会变

**Comment by sidious-82** [comment]
那能不能考虑下保存

你想一下这样的场景

雷神和九条都是用绝缘的，还是都用雷伤杯，也就是说我想优先保证雷神的装备，雷神用的九条就不会再用了。

那么我会保存一个雷神的装备，让九条配装的时候排除掉，这样我就不需要每次都一个一个的禁用圣遗物，用完之后还经常忘记改回来了。

变的话无所谓呀，你想如果我雷神改了装备，就覆盖套装，这样九条也就能排除掉新的雷神圣遗物了。
