### ISSUE TITLE
建议修改「禁用/启用」图标

### ISSUE THREAD

**Issue by wr786** [wormtql/genshin_artifact#13]
![image](https://user-images.githubusercontent.com/32223541/110323166-2c5d0f00-804f-11eb-9532-953b171a037f.png)

如图，现在单独圣遗物的「禁用/启用」图标是这个，但是这并不是很容易联想到禁用。（挺像PhotoShop的“裁剪”）

![image](https://user-images.githubusercontent.com/32223541/110323217-4565c000-804f-11eb-8d33-df51a81066a3.png)

而作为对比，「禁用全部/启用全部」的这个🔒图标表意就很明显。

从风格统一来考虑，也应该考虑将单独圣遗物的「禁用/启用」图标换成🔒

**Comment by wormtql** [comment]
确实，会在下版本中改掉 😃

**Comment by wormtql** [comment]
已修改
