### ISSUE TITLE
5.0以后充能需求过滤不精确，以及几个问题

### ISSUE THREAD

**Issue by chongshan0** [wormtql/genshin_artifact#130]
5.0之后用下来几个问题：
1、充能需求过滤不精确，比如设定2.0，会出来190+充能的结果（纯枚举）
2、目标函数下的充能需求，和计算设置里的最小充能，两个有什么区别，能否只保留一个
3、保存预设，“计算设置”没有被保存下来

**Comment by chongshan0** [comment]
另外，目标函数似乎少了一些：
1、最高单属性，比如最高暴击率，配合西风武器还挺有用的
2、最高期望伤害（可以指定aeq，无反应的伤害）

**Comment by Heyedanlty** [comment]
目标函数也应该有一个：
1.最大元素充能效率
这个对于一些辅助还很关键，比如莫娜之类的
