### ISSUE TITLE
圣遗物限定套装设置，建议增加等效二件套同时计算的选项（仅限2+2筛选时可选择）

### ISSUE THREAD

**Issue by SummerX9** [wormtql/genshin_artifact#133]
2.6新圣遗物实装后，二件套效果为“攻击力提高18%”的五星圣遗物套装达到4套，建议增加等效二件套同时计算的选项。

举例：
如新增一个名为“角斗士类”的选项，仅能在事先点选其它套装（不含角斗士、追忆、辰砂、余响）后才能选择。
以如雷+“角斗士类“为例，双选后计算器返回符合条件的如雷2+角斗士2/追忆2/辰砂2/余响2的计算结果。
五星中少女/海染二件套同理可以新增”少女类”，亦可考虑四星圣遗物中的等效情况。

再次感谢大佬开发出这么棒的原神工具，祝好！

**Comment by wormtql** [comment]
这比较难，建议不限定套装
