### ISSUE TITLE
新加的dockerfile有点小问题

### ISSUE THREAD

**Issue by shisu3613** [wormtql/genshin_artifact#140]
dockerfile 用的是node:14-alpine， alpine版本的node是不带git的。所以要么去掉alpine，要么在这句话下面加上RUN apk update && apk add git, 像这样：
<img width="477" alt="屏幕截图 2022-04-09 210133" src="https://user-images.githubusercontent.com/48946918/162575255-7d67f6a2-6a1f-43f4-afe4-051dccefd0a8.png">

**Comment by wormtql** [comment]
https://github.com/wormtql/genshin_artifact/commit/6855af89f5ea51cc249de425520ec3bd2dc54645
