### ISSUE TITLE
胡桃的目标函数好像计算有误

### ISSUE THREAD

**Issue by Ruby280255768** [wormtql/genshin_artifact#146]
![image](https://user-images.githubusercontent.com/18400004/165773460-af70ae09-2f2f-437f-ab89-edf7c5fd123e.png)
![image](https://user-images.githubusercontent.com/18400004/165773576-650ce820-e481-4a0d-8d25-79d5f92ce62d.png)
![image](https://user-images.githubusercontent.com/18400004/165773665-eb8a0f81-3716-4471-a508-ab433e70cb79.png)
图1为默认计算设置的结果，推荐追忆套，期望蒸发伤害约为4w；
图2为限定魔女套的计算结果，期望约为4.6w；
图3未限定魔女套+乐团的计算结果，期望约为4.9w（该结果为旧版本占卜铺推荐的套装）；
请问为什么默认设置下，结算推荐的结果并非最优解？
[mona.zip](https://github.com/wormtql/genshin_artifact/files/8583588/mona.zip)
附上yas扫描的圣遗物结果

**Comment by wormtql** [comment]
如图是默认配置，那么蒸发只占50%，如果希望完全使得蒸发伤害最大，把蒸发拉到1

**Comment by Ruby280255768** [comment]
> 如图是默认配置，那么蒸发只占50%，如果希望完全使得蒸发伤害最大，把蒸发拉到1

![image](https://user-images.githubusercontent.com/18400004/165780497-6aa8b209-15f8-4e66-a892-1838b4cc5d6e.png)
一样的，除非限制圣遗物套装，不然推荐套装都是追忆套

**Comment by wormtql** [comment]
默认胡桃E技能会把追忆套效果拉满，如果不喜欢追忆套，需要去圣遗物设置里改为手动，并且不把追忆套拉满

**Comment by Ruby280255768** [comment]
> 默认胡桃E技能会把追忆套效果拉满，如果不喜欢追忆套，需要去圣遗物设置里改为手动，并且不把追忆套拉满

呃，不是不喜欢哪个圣遗物套装的意思，按照这个计算结果，追忆套的伤害不是更低吗？还是我哪里理解错了？

**Comment by wormtql** [comment]
你应该把中间的圣遗物里的追忆效果拉满

**Comment by Ruby280255768** [comment]
> 你应该把中间的圣遗物里的追忆效果拉满

原来如此，明白了，感谢！

**Comment by Ruby280255768** [comment]
> 你应该把中间的圣遗物里的追忆效果拉满

不好意思，再请教一下，追忆套持续10秒，胡桃e冷却时间16秒，追忆的覆盖率是62.5%吧，那中间这个进度拉满是把覆盖率当做100%吗？还是说在62.5%的基础上再乘算的一个系数？

**Comment by wormtql** [comment]
拉满。中间的条只影响算伤害，左边的圣遗物配置影响配装

**Comment by Ruby280255768** [comment]
> 拉满。中间的条只影响算伤害，左边的圣遗物配置影响配装

谢谢
