### ISSUE TITLE
圣遗物推荐考虑套装效果吗？

### ISSUE THREAD

**Issue by NocturneMao** [wormtql/genshin_artifact#148]
网页安利给朋友了，测试的迪卢克魔女套，网页给我推荐的是2角斗士2宗师，是不是只考虑了双攻双爆，没考虑魔女套的火伤和队伍的蒸发？网页给的精通沙漏、百分比攻击面具和面具。

选的整队优化，队伍是迪卢克雷神行秋七七，比重是0.4、0.3、0.2、0.1.

**Comment by wormtql** [comment]
不同的目标函数会有默认的圣遗物参数。可以自己通过圣遗物设置去配置。
