### ISSUE TITLE
计算“通用”目标函数时增加对于伤害类型的选择（A/E/Q的各段伤害）

### ISSUE THREAD

**Issue by wa3y** [wormtql/genshin_artifact#149]
比如，现在好像没有办法计算类似北斗Q，香菱Q的最优圣遗物（没搞错的话，绝缘特效应该是没有计入，也没有看到选择的地方）

更具体地说，显示伤害计算结果的地方能够分开处理各个技能的各段伤害，但是目标函数却不能选择，造成了一些困扰

**Comment by wormtql** [comment]
香菱默认函数就是Q技能伤害，绝缘是计入的。

**Comment by wormtql** [comment]
因为我个人认为针对单个技能的配装意义不太大，很多人都是复合的输出，除了一些几乎只用大招的副C

**Comment by wa3y** [comment]
但是这样的话就涉及一个“流派”的问题，比如北斗进武装队，不弹反的情况下应该是Q伤害占比远远大于E，与现有”普通北斗弹反流”的目标函数大不相符，又例如不同人对于行秋EQ伤害占比的理解不同，以及有一些武神钟离之类的特殊用法

**Comment by chongshan0** [comment]
个人赞同wa3y的观点，目前的预设模板其实很难满足自定义流派的需求，而且也没有说明计算方式，结果有时很难理解。
比如行秋评分最高的一套，Q伤害反而比较低。

**Comment by wormtql** [comment]
DSL可以满足要求
