### ISSUE TITLE
圣遗物评分系统中似乎没有对只能强化6次以及一些数值做约束

### ISSUE THREAD

**Issue by DangeRS2** [wormtql/genshin_artifact#151]
我可能在做一个无聊的测试，试图寻找圣遗物的满分是多少。但是，当给副词条暴击伤害输入到100%时，仍可以得出分数，这也就是说明，评分系统的分数没有上限。但实际情况是，5星极品强化，暴伤只能达到46.6%，有没有可能对评分约束并归一化一下？

**Comment by wormtql** [comment]
单次强化的最大值为1分，所以如果是默认设置满分是8分

**Comment by DangeRS2** [comment]
明白了，这个5星极品强化暴伤头，只开暴伤权重为1，满分6分，确实默认设置（暴伤+暴击+攻击%）下，满分为8分。

但是为什么还有小数点呀？

![截屏2022-05-03 下午11 12 20](https://user-images.githubusercontent.com/49086184/166618562-f0804540-3494-421b-8b73-d77b985d0e90.png)

**Comment by wormtql** [comment]
数值精度问题
