### ISSUE TITLE
是否可以引入新的圣遗物评分标准？

### ISSUE THREAD

**Issue by NocturneMao** [wormtql/genshin_artifact#155]
目前的圣遗物潜力评分是按照给定词条手动赋权的，词条的权值影响了圣遗物的评分，而“手动赋权”受主观判断影响较大，未必能较好描述圣遗物真实潜力，而引入一套受多数人认同的评分系统可以很大程度上避免这一问题。

最近在米游社看到一个帖子【1】，对圣遗物的有效词条进行了分类以及折算，相对目前占卜铺使用的标准，主要有以下三个优势：
1）词条权值基于游戏内满级圣遗物的相应最大属性值，出分更可靠；
2）分值从目前的个位数提升到20左右（20级圣遗物），方便玩家对不同圣遗物作比较；
3）直接给出评价结果（是否毕业，是否保留胚子），方便玩家做出判断。

知名原神主播雷雨Lyy也在使用类似的圣遗物评价标准【2】，并于近日得到高达50.6分的水伤杯【3】（满分54.6）。

【1】【V2.6攻略】#其他攻略#圣遗物评分如何计算？-原神社区-米游社
https://bbs.mihoyo.com/ys/article/20992133

【2】【圣遗物评分系统科普】40分圣遗物为什么会这么稀有-原神社区-米游社
https://bbs.mihoyo.com/ys/article/19415958

【3】雷雨Lyy的个人空间_哔哩哔哩_bilibili
https://space.bilibili.com/17603188/dynamic

**Comment by wormtql** [comment]
目前莫娜的评分系统也是基于每次强化的最大值，跟【1】是等价的，【1】的分数只是莫娜的常数倍，可以认为是莫娜的权值都为1的情况。
评价标准【2】的pvp意义大于实际意义，因为各种数据证明，大公鸡跟双爆同样重要

**Comment by mzname** [comment]
> 目前莫娜的评分系统也是基于每次强化的最大值，跟【1】是等价的，【1】的分数只是莫娜的常数倍，可以认为是莫娜的权值都为1的情况。 评价标准【2】的pvp意义大于实际意义，因为各种数据证明，大公鸡跟双爆同样重要

请问之前是3.0+以上的建议保留，那现在的话
在默认的大攻击双爆权重1的时候，建议保留哪些胚子呢？

**Comment by wormtql** [comment]
#243
