### ISSUE TITLE
能否每次导入圣遗物后自动保存在本地mona文件夹内

### ISSUE THREAD

**Issue by forchannot** [wormtql/genshin_artifact#164]
然后让每次npm启动时自动加载该数据，现在每次启动圣遗物都不在了得重新导入一次，每次都手动保存下来略嫌麻烦

**Comment by wormtql** [comment]
是会自动保存的，没有保存可能是bug，刷新看看

**Comment by forchannot** [comment]
> 是会自动保存的，没有保存可能是bug，刷新看看

请问我重新装了一次出现这个怎么解决呢
![image](https://user-images.githubusercontent.com/100580891/177556806-e56e4c8e-5e2b-4bfd-bd51-a339e8e2d4d4.png)
rust工具链应该都装好了的

**Comment by wormtql** [comment]
你是在自己部署？还是在干啥
