### ISSUE TITLE
自行编译时报错

### ISSUE THREAD

**Issue by forchannot** [wormtql/genshin_artifact#165]
npm run serve时报错
![image](https://user-images.githubusercontent.com/100580891/177684759-57978950-1ffc-4605-8f89-fa8710ced8cb.png)
![image](https://user-images.githubusercontent.com/100580891/177684808-ea4fb19d-d8d0-4270-a9ea-ee2473f3e4f9.png)
还有一些，不过都是类似的报错

**Comment by wormtql** [comment]
只是要使用的话直接访问网站就好了，自己编译的话参考readme

**Comment by forchannot** [comment]
> 只是要使用的话直接访问网站就好了，自己编译的话参考readme

就是参考的readme来的，编译报错

**Comment by wormtql** [comment]
你运行npm run build:wasm了吗

**Comment by forchannot** [comment]
> 你运行npm run build:wasm了吗

运行了

**Comment by forchannot** [comment]
> 你运行npm run build:wasm了吗

如果直接用网页版的，我的数据怎么保存呢，比如我设置好的圣遗物套装组，计算预设等等

**Comment by wormtql** [comment]
数据会自动保存的，没保存可能是你浏览器设置的问题
