### ISSUE TITLE
女仆白影剑/螭骨剑精炼伤害计算结果有问题

### ISSUE THREAD

**Issue by DefetC** [wormtql/genshin_artifact#17]
把白影剑/螭骨剑从1精改为5精，计算出来的伤害期望没有改变。这两把武器是没有计算被动吗？还是说所有的武器都不计算被动？还是说考虑被动了，但是没有考虑精炼的提升？

**Comment by wormtql** [comment]
这两把剑的被动过于动态（要叠加的），没法很精确的计算，因此没有算入。其他的某些武器如果被动非常静态，比如黑剑的伤害提升，那会计入。另外不管算不算被动，对配装的影响可以忽略，配装那边的数值是用于比较大小的，不是期望伤害，例如要算期望伤害那么技能倍率无论如何都一样，因此不会乘倍率，因为那个数值只是用于比大小，而不是真正的期望伤害。
