### ISSUE TITLE
计算过程发生错误：Uncaught RuntimeError: unreachable

### ISSUE THREAD

**Issue by NocturneMao** [wormtql/genshin_artifact#170]
人物参数比游戏里的设置还低一些，也显示错误，没有输出结果。

**Comment by NocturneMao** [comment]
没事了，宗室少一个，估计是套装数量不符合。

**Comment by SirusChen** [comment]
请问一下，我也遇到了这样的问题。【套装数量不符合】要怎么样修正？

**Comment by NocturneMao** [comment]
> 

以我的为例，宗师的圣遗物总数量够了，但是一半是花，其他的就一个，计算的时候很可能会分配不出来。最好的解决办法就是再刷两天本，攒几个不同位置的胚子，或者计算的时候不选择只配置宗室套。
