### ISSUE TITLE
如何设置圣遗物计算的标准？

### ISSUE THREAD

**Issue by karaikyo** [wormtql/genshin_artifact#174]
比如八重神子，如果以E的伤害为标准，精通沙可能会比攻击沙好；如果以Q的伤害为标准，攻击沙则优于精通沙。有没有地方可以设置这个标准呢？

**Comment by wormtql** [comment]
没有完美标准，只能根据自己的经验

**Comment by karaikyo** [comment]
> 没有完美标准，只能根据自己的经验

这个理解，不过想知道有没有可能支持自定义标准呢？另外在哪可以查看角色的默认的具体计算标准呢？

**Comment by wormtql** [comment]
可以自定义，用MonaDSL（但是这个功能尚未上线文档），可以在本仓库的actions里面找到部分文档。默认的标准可以看源代码
