### ISSUE TITLE
某个圣遗物录入有误，但是找不出来

### ISSUE THREAD

**Issue by SirusChen** [wormtql/genshin_artifact#175]
录入圣遗物后，进入计算器，进行计算，一直返回【计算有误】。
估计是某个圣遗物有问题，因为清空后，手动录入一个新的是没问题的。

js/524.a9dada37.js:1 panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 5987)', src/applications/optimize_artifacts/interface_wasm.rs:32:63

Stack:

Error
    at G (https://mona-uranai.com/js/524.a9dada37.js:1:20118)
    at https://mona-uranai.com/67e2cd77c7079ea3.module.wasm:wasm-function[916]:0x1438d3
    at https://mona-uranai.com/67e2cd77c7079ea3.module.wasm:wasm-function[3016]:0x1801d6
    at https://mona-uranai.com/67e2cd77c7079ea3.module.wasm:wasm-function[1289]:0x162e70
    at https://mona-uranai.com/67e2cd77c7079ea3.module.wasm:wasm-function[1476]:0x16b73f
    at https://mona-uranai.com/67e2cd77c7079ea3.module.wasm:wasm-function[2021]:0x1787cf
    at https://mona-uranai.com/67e2cd77c7079ea3.module.wasm:wasm-function[2185]:0x17ad11
    at https://mona-uranai.com/67e2cd77c7079ea3.module.wasm:wasm-function[1513]:0x16cb6d
    at https://mona-uranai.com/67e2cd77c7079ea3.module.wasm:wasm-function[87]:0x49601
    at https://mona-uranai.com/67e2cd77c7079ea3.module.wasm:wasm-function[2033]:0x178a80

J @ js/524.a9dada37.js:1
$func916 @ 67e2cd77c7079ea3.module.wasm:1
$func3016 @ 67e2cd77c7079ea3.module.wasm:1
$func1289 @ 67e2cd77c7079ea3.module.wasm:1
$func1476 @ 67e2cd77c7079ea3.module.wasm:1
$func2021 @ 67e2cd77c7079ea3.module.wasm:1
$func2185 @ 67e2cd77c7079ea3.module.wasm:1
$func1513 @ 67e2cd77c7079ea3.module.wasm:1
$func87 @ 67e2cd77c7079ea3.module.wasm:1
$optimizesinglewasm_optimize @ 67e2cd77c7079ea3.module.wasm:1
optimize @ js/524.a9dada37.js:1
self.onmessage @ 650.4f3dd798.js:1

**Comment by wormtql** [comment]
麻烦提供一下圣遗物文件

**Comment by SirusChen** [comment]
你好，这是 json。不知道该如何检查其正确性

**Comment by wormtql** [comment]
如果还有问题可以重开一个issue
