### ISSUE TITLE
Suggestion: 在计算器和多人优化中将未满级圣遗物主词条按满级数值参与计算

### ISSUE THREAD

**Issue by yippp** [wormtql/genshin_artifact#176]
圣遗物主词条的属性值和等级的对应关系是确定的。一个建议是可以加上一个选项，将主词条的属性值按20级或指定等级计算。这样在计算圣遗物搭配时能考虑暂未升级等级的圣遗物。现在因为无此功能，低等级和高等级的圣遗物属性差异过大，低等级圣遗物基本不会被考虑，部分拉满等级（就算小词条全歪依然优质）的圣遗物会被忽略。

**Comment by wormtql** [comment]
暂不考虑此功能
1. 副词条影响很大
2. 会导致参与计算的圣遗物数量巨大，难以计算得到结果
