### ISSUE TITLE
How to export artifacts in my pack？

### ISSUE THREAD

**Issue by xesdiny** [wormtql/genshin_artifact#18]
I find the introductions about API json style in link[https://wormtql.gitbook.io/mona-uranai/].
But where’s the json in my account?

**Comment by wormtql** [comment]
you cannot export json natively from your game, you can only use third party tools to export json from the game.
but such kinds of tools are not quite developed, here is an example using OCR to export json(english version currenly not supported): [`link`](https://github.com/ChanIok/JumpyDumpty)
the link "https://wormtql.gitbook.io/mona-uranai/" is just an interface, anyone can develop a tool to export artifacts into this format.
