### ISSUE TITLE
建议加一个按照圣遗物潜力进行优化的选项

### ISSUE THREAD

**Issue by likan999** [wormtql/genshin_artifact#189]
作为萌新，大量圣遗物都是胚子或者低等级。希望挑选出适合某角色的胚子进行强化。能否加一个选项，不到20级的，按照20级的期望属性来进行计算？这个20也可以作为选项，比如我只希望强化到12级，那么能不能不到12级的，按照12级的期望属性来进行计算？谢谢大佬

**Comment by wormtql** [comment]
计算复杂度太高，不考虑
