### ISSUE TITLE
甘雨天赋【唯此一心】的20%暴击率感觉放在Buff里更适合

### ISSUE THREAD

**Issue by chtholist** [wormtql/genshin_artifact#201]
甘雨天赋【唯此一心】的20%暴击率现在是放在伤害计算里，圣遗物配置时没有考虑，感觉放在Buff里更适合，计算圣遗物时应该考虑这20%暴击率
ps. Ysin默认加上这20%暴击率

**Comment by Fachep** [comment]
目标函数有考虑这个天赋，另外此类天赋放在这里（SkillConfig）可以使dsl做些更复杂的计算
