### ISSUE TITLE
妮露生命的圣遗物的词条计算与游戏中有误差

### ISSUE THREAD

**Issue by Blackmegg1** [wormtql/genshin_artifact#209]
这是计算结果 32100.465：
![屏幕截图 2022-10-18 214102](https://user-images.githubusercontent.com/59142114/196446524-886ea8ac-4fca-4ac7-8bed-9e7dceabbf30.png)
游戏中相同的圣遗物则是 32108：
![屏幕截图 2022-10-18 214319](https://user-images.githubusercontent.com/59142114/196447024-79649ac6-5bf3-411b-96d7-99c75c852128.png)

**Comment by wormtql** [comment]
这个在可接受的误差范围内，因为扫描得到的数值不是游戏内部全精度的数值
