### ISSUE TITLE
玛海菈的水色/流浪的晚星/西福斯的月光武器效果有误

### ISSUE THREAD

**Issue by Semidio** [wormtql/genshin_artifact#215]
玛海菈的水色/流浪的晚星/西福斯的月光计算中可以不正常的吃到砂糖天赋2，纳西妲天赋1，圣显之钥等由其他属性转化的元素精通带来的额外转化加成。

**Comment by panganqi** [comment]
同样的，赤沙也不应该吃到草神的天赋250精通
