### ISSUE TITLE
2元素+2攻击/2精通的限定套装设置

### ISSUE THREAD

**Issue by zhangyina1** [wormtql/genshin_artifact#227]
希望可以增加2元素加成+2攻击/2精通的组合方式，2件套攻击加成有四种了，萌新每样都只有四五个所以要算出来单人最佳要计算4次，多人优化就是指数上升的计算次数再比较了。。

举个例子就是
![图层 8](https://user-images.githubusercontent.com/38777924/204097358-b61fea71-1abf-47ed-b998-2fac90aad25c.png)

**Comment by wormtql** [comment]
单人优化可以不加任何限制，得到的就是最优
