### ISSUE TITLE
在计算非攻击力倍率的技能时，结果出错

### ISSUE THREAD

**Issue by realxuzijun** [wormtql/genshin_artifact#228]
如果我选择夜兰，e技能蒸发期望最高时，计算结果所选时之沙为攻击沙，但该技能倍率为生命值倍率。
怀疑该期望逻辑是攻击倍率*其他系数，而非生命倍率*其他系数。

**Comment by wormtql** [comment]
选择角色本身的专属目标函数，通用函数是这样的
