### ISSUE TITLE
扫描完成后没有自动导入到占卜铺中

### ISSUE THREAD

**Issue by kido113** [wormtql/genshin_artifact#238]
![捕获](https://user-images.githubusercontent.com/30402674/210076262-3b4cc942-496d-40dd-b27e-5399c34d0f48.PNG)
![捕获2](https://user-images.githubusercontent.com/30402674/210076299-288d63ac-25de-44a0-b779-5f59e4555cf4.PNG)

**Comment by wormtql** [comment]
扫描失败了，可能游戏背包圣遗物详情没拉到最上面

**Comment by kido113** [comment]
> 

应该不是这个原因，重新试了几次，确定拉到顶了

**Comment by wormtql** [comment]
那试试直接用yas.exe，最好附上游戏截图，以及yas最开始的输出内容

**Comment by kido113** [comment]
![捕获](https://user-images.githubusercontent.com/30402674/210077234-5efadd5b-f938-4106-ae7e-0d8a8ca594c6.PNG)
![游戏](https://user-images.githubusercontent.com/30402674/210077438-fca35d93-b451-4e10-8610-ef86077ef1f3.PNG)
是这两个截图吗

**Comment by kido113** [comment]
好像是yas出现bug了，在nga的yas讨论贴里看到一样的问题

**Comment by wormtql** [comment]
确实没拉到最上面，手动往下拉一下

**Comment by kido113** [comment]
啊，好神奇，感谢！
