### ISSUE TITLE
2+2搭配下剩余的散件锁定功能

### ISSUE THREAD

**Issue by Sephiroth0705** [wormtql/genshin_artifact#259]
在当前的2+2套装限制中，余下的散件是随机给出的。我遇到的问题是：我有一个极品的水伤杯（风套）不属于2+2套装（2沉沦2千岩）范围内，那么这个水伤杯将无法被选中，需要人为另行搭配。最终手搓的搭配伤害期望是比模型给出的高。以此为例，是否可以为2+2余下的散件增添锁定功能，让模型在剩下的四个圣遗物再自行搭配2+2?

**Comment by wormtql** [comment]
如果没选极品水伤杯，那就说明在这个目标下水伤杯不是最好的选择。手搓的圣遗物可能导致某个技能期望变大，但是一套流程的总伤害可能变小
