### ISSUE TITLE
导出 json 中的浮点数不是精确数值

### ISSUE THREAD

**Issue by yinxin630** [wormtql/genshin_artifact#27]
如图所示:
![image](https://user-images.githubusercontent.com/6939365/112859750-b8f66c80-90e5-11eb-9d10-33d178a4fa80.png)

**Comment by yinxin630** [comment]
不知道导入的时候是否有问题, 待测试

**Comment by wormtql** [comment]
这应该是JSON序列化时的默认行为，感觉影响不大，除了会增大导出体积
