### ISSUE TITLE
关于林尼礼花术弹伤害倍率错误

### ISSUE THREAD

**Issue by Andrea-lyz** [wormtql/genshin_artifact#294]
林尼礼花术弹伤害倍率错误反馈
相同面板及增益下，莫娜占卜铺给出的礼花术弹暴击伤害居然比隐具魔术箭暴击伤害还低
前者倍率381% 后者倍率311%
根据我的测试 双火 钟离减抗条件下
暴击伤害       隐具魔术箭       礼花术弹
实际                 39791               59053
莫娜面板          38438               37668
魔术箭误差正常，但这个礼花术弹差得有些远了

![屏幕截图 2023-09-04 015820](https://github.com/wormtql/genshin_artifact/assets/52863141/381bf3d5-947a-4ca4-b52f-e4056b881663)

![原神 2023-09-04 02-14-28 mp4_20230904_021755 548](https://github.com/wormtql/genshin_artifact/assets/52863141/75b34b67-a0b0-43b4-b4b0-d126f4de0a18)

**Comment by wormtql** [comment]
隐具魔术箭有天赋1加成，礼花术弹没有，至于为什么与游戏差这么多，我也不清楚，你可以打开明细看看是不是所有buff都在了

**Comment by Andrea-lyz** [comment]
> 隐具魔术箭有天赋1加成，礼花术弹没有，至于为什么与游戏差这么多，我也不清楚，你可以打开明细看看是不是所有buff都在了
固有天赋1.惊险演出
如果林尼通过发射隐具魔术箭消耗了生命值，该隐具魔术箭召唤的`怪笑猫猫帽`命中敌人时会为林尼恢复3点元素能量，并且基于攻击力的80%提高造成的伤害。
礼花弹术是能吃到天赋1的80%加成的，魔术箭没有吃天赋1

**Comment by Andrea-lyz** [comment]
> 隐具魔术箭有天赋1加成，礼花术弹没有，至于为什么与游戏差这么多，我也不清楚，你可以打开明细看看是不是所有buff都在了

固有天赋1.惊险演出
如果林尼通过发射隐具魔术箭消耗了生命值，该隐具魔术箭召唤的`怪笑猫猫帽`命中敌人时会为林尼恢复3点元素能量，并且基于攻击力的80%提高造成的伤害。
礼花弹术是能吃到天赋1的80%加成的，魔术箭没有吃天赋1
