### ISSUE TITLE
提示"没有合适的圣遗物"

### ISSUE THREAD

**Issue by ledong1** [wormtql/genshin_artifact#3]
添加两套圣遗物后,先查看了可莉的期望火伤,再查看迪卢克时, 选任意或只限4件魔女套都出现了提示"没有合适的圣遗物". 
刷新网页后正常.

**Comment by wormtql** [comment]
可以提供一下导出的json字符串吗，还有你选的目标函数、武器等，
或者提供一下复现这个bug的方法

**Comment by ledong1** [comment]
{"flower":[{"setName":"crimsonWitch","position":"flower","detailName":"魔女的炎之花","mainTag":{"name":"lifeStatic","value":4780},"normalTags":[{"name":"critical","value":0.031},{"name":"criticalDamage","value":0.132},{"name":"attackStatic","value":33},{"name":"defendPercentage","value":0.175}],"omit":false,"id":0},{"setName":"crimsonWitch","position":"flower","detailName":"魔女的炎之花","mainTag":{"name":"lifeStatic","value":4780},"normalTags":[{"name":"critical","value":0.062},{"name":"attackPercentage","value":0.08199999999999999},{"name":"attackStatic","value":19},{"name":"elementalMastery","value":54}],"omit":false,"id":1}],"feather":[{"setName":"crimsonWitch","position":"feather","detailName":"魔女常燃之羽","mainTag":{"name":"attackStatic","value":311},"normalTags":[{"name":"critical","value":0.054000000000000006},{"name":"criticalDamage","value":0.14800000000000002},{"name":"lifeStatic","value":568},{"name":"defendPercentage","value":0.131}],"omit":false,"id":3},{"setName":"crimsonWitch","position":"feather","detailName":"魔女常燃之羽","mainTag":{"name":"attackStatic","value":311},"normalTags":[{"name":"attackPercentage","value":0.057999999999999996},{"name":"criticalDamage","value":0.19399999999999998},{"name":"recharge","value":0.057999999999999996},{"name":"elementalMastery","value":65}],"omit":false,"id":4}],"sand":[{"setName":"crimsonWitch","position":"sand","detailName":"魔女破灭之时","mainTag":{"name":"attackPercentage","value":0.466},"normalTags":[{"name":"attackStatic","value":51},{"name":"criticalDamage","value":0.14},{"name":"recharge","value":0.052000000000000005},{"name":"lifeStatic","value":538}],"omit":false,"id":5},{"setName":"crimsonWitch","position":"sand","detailName":"魔女破灭之时","mainTag":{"name":"attackPercentage","value":0.466},"normalTags":[{"name":"critical","value":0.09699999999999999},{"name":"criticalDamage","value":0.062},{"name":"defendPercentage","value":0.057999999999999996},{"name":"defendStatic","value":51}],"omit":false,"id":6}],"cup":[{"setName":"archaicPetra","position":"cup","detailName":"巉岩琢塑之樽","mainTag":{"name":"fireBonus","value":0.466},"normalTags":[{"name":"attackPercentage","value":0.146},{"name":"criticalDamage","value":0.14800000000000002},{"name":"elementalMastery","value":16},{"name":"defendPercentage","value":0.124}],"omit":false,"id":7},{"setName":"blizzardStrayer","position":"cup","detailName":"历经风雪的思念","mainTag":{"name":"fireBonus","value":0.466},"normalTags":[{"name":"critical","value":0.039},{"name":"criticalDamage","value":0.109},{"name":"lifePercentage","value":0.053},{"name":"elementalMastery","value":89}],"omit":false,"id":8}],"head":[{"setName":"crimsonWitch","position":"head","detailName":"焦灼的魔女帽","mainTag":{"name":"critical","value":0.311},"normalTags":[{"name":"defendPercentage","value":0.129},{"name":"recharge","value":0.065},{"name":"attackPercentage","value":0.198},{"name":"attackStatic","value":31}],"omit":false,"id":9},{"setName":"crimsonWitch","position":"head","detailName":"焦灼的魔女帽","mainTag":{"name":"criticalDamage","value":0.622},"normalTags":[{"name":"defendPercentage","value":0.109},{"name":"recharge","value":0.052000000000000005},{"name":"critical","value":0.10099999999999999},{"name":"attackStatic","value":45}],"omit":false,"id":10}]}
可莉,80-,天空书,80-,期望火伤,4魔女,
返回角色
迪卢克,90,螭骨剑,90,角色专属迪卢克,任意,
我自己又试了一遍,没有复现成功,清除cookie导入json,同样没有复现成功...
奇怪的bug...会不会是我chrome标签页开的太多导致的?(大概开了80个吧orz)

**Comment by wormtql** [comment]
我也没有复现成功，就当没出现这问题好了（手动狗头）

**Comment by ledong1** [comment]
诶嘿（话说大佬可以推荐点vue教程吗？

**Comment by wormtql** [comment]
教程当然是官方文档的好，多写项目才是正道（这种话肯定早就听厌了）。我也不是啥大佬，我就是纯个人经验 😃

**Comment by ledong1** [comment]
确实，是时候再写个网站了，听说vue不错，看起来比flask好多了
