### ISSUE TITLE
希望计算结果还可以列出第二期望、第三期望、甚至第四期望

### ISSUE THREAD

**Issue by hezheka** [wormtql/genshin_artifact#35]
如题，配队是配四人队，希望队伍输出能平滑一点，所以有时会考虑牺牲主角色的一点输出，把更好的圣遗物让给别人。这个时候第二期望、第三期望就有意义了。虽然直接锁圣遗物也可以，但是就要重新计算，浪费时间，浪费服务器算力。

**Comment by wormtql** [comment]
安排
