### ISSUE TITLE
希望能在得出的期望伤害旁，附加一个暴击时和不暴击时的具体值

### ISSUE THREAD

**Issue by hezheka** [wormtql/genshin_artifact#37]
只是一个小小小的建议，这些数值可以作为这个“仅供参考”的期望数值的一个补充说明，殴打对象选80级丘丘人就好了~

**Comment by wormtql** [comment]
这个有点难，因为有不同的buff，我打算做个大版本更新实现这个功能

**Comment by hezheka** [comment]
说得对，是我想当然了。[攻击buff][增伤buff][爆伤buff][倍率buff][减抗buff][减防buff][精通buff][攻速buff]，您是想能让旅行者能够自行勾选想要的buff，然后计算出期望并得出具体值吗？辛苦大大了，工作量挺大的。
