### ISSUE TITLE
几条功能建议

### ISSUE THREAD

**Issue by qstdnx** [wormtql/genshin_artifact#38]
①无法模拟莫娜星异状态下伤害期望：莫娜作为副c，大部分伤害都在星异状态下打出，星异状态下最高60%元素增伤，这对配装的影响是很大的，加上现在有莫甘娜阵容延长星异持续时间，可能其他角色也需要算星异状态下的配装，比如甘雨温迪等。
②圣遗物编辑不能直接更改套装：我使用cocogoat导入的圣遗物，所有的流浪沙漏都被识别成了如雷，但是我发现不能直接更改套装，反而要删掉重新输入。
③希望能直接更改预设名字，以及导出预设。
④希望计算结果能按期望从高到低列几行，类似这个伤害计算器
https://genshin.mingyulab.com/artifact_set_compare/artifact_set_compare
比如设置成最优搭配，次选搭配，妥协搭配，捡破烂搭配之类的(◔◡◔)最大伤害也能标注上，这样能更好的分配每个角色的圣遗物。

**Comment by qstdnx** [comment]
@wormtql 计算出现问题，北斗688，1命80+，武器90狼末1精，目标为大招雷伤，无buff，算140充能下伤害期望最大，计算结果用的火伤杯治疗头(¯―¯٥)以下是我的圣遗物。
{"flower":[{"setName":"bloodstainedChivalry","detailName":"染血的铁之心","position":"flower","mainTag":{"name":"lifeStatic","value":4780},"normalTags":[{"name":"critical","value":0.031000000000000003},{"name":"elementalMastery","value":44},{"name":"attackPercentage","value":0.14},{"name":"criticalDamage","value":0.187}],"omit":false,"level":20,"star":5,"id":349},{"setName":"maidenBeloved","detailName":"远方的少女之心","position":"flower","mainTag":{"name":"lifeStatic","value":4780},"normalTags":[{"name":"lifePercentage","value":0.111},{"name":"defendPercentage","value":0.12400000000000001},{"name":"defendStatic","value":60},{"name":"attackStatic","value":39}],"omit":false,"level":20,"star":5,"id":350},{"setName":"heartOfDepth","detailName":"饰金胸花","position":"flower","mainTag":{"name":"lifeStatic","value":4780},"normalTags":[{"name":"criticalDamage","value":0.20199999999999999},{"name":"defendStatic","value":42},{"name":"critical","value":0.054000000000000006},{"name":"lifePercentage","value":0.053}],"omit":false,"level":20,"star":5,"id":351},{"setName":"noblesseOblige","detailName":"宗室之花","position":"flower","mainTag":{"name":"lifeStatic","value":4780},"normalTags":[{"name":"attackPercentage","value":0.053},{"name":"critical","value":0.12400000000000001},{"name":"recharge","value":0.11699999999999999},{"name":"attackStatic","value":16}],"omit":false,"level":20,"star":5,"id":352},{"setName":"noblesseOblige","detailName":"宗室之花","position":"flower","mainTag":{"name":"lifeStatic","value":4780},"normalTags":[{"name":"criticalDamage","value":0.054000000000000006},{"name":"recharge","value":0.057999999999999996},{"name":"critical","value":0.035},{"name":"defendPercentage","value":0.306}],"omit":false,"level":20,"star":5,"id":353},{"setName":"noblesseOblige","detailName":"宗室之花","position":"flower","mainTag":{"name":"lifeStatic","value":4780},"normalTags":[{"name":"recharge","value":0.12300000000000001},{"name":"defendStatic","value":60},{"name":"critical","value":0.066},{"name":"lifePercentage","value":0.047}],"omit":false,"level":20,"star":5,"id":354},{"setName":"crimsonWitch","detailName":"魔女的炎之花","position":"flower","mainTag":{"name":"lifeStatic","value":4780},"normalTags":[{"name":"attackStatic","value":14},{"name":"criticalDamage","value":0.12400000000000001},{"name":"critical","value":0.14},{"name":"elementalMastery","value":21}],"omit":false,"level":20,"star":5,"id":355},{"setName":"thunderingFury","detailName":"雷鸟的怜悯","position":"flower","mainTag":{"name":"lifeStatic","value":4780},"normalTags":[{"name":"elementalMastery","value":21},{"name":"recharge","value":0.188},{"name":"critical","value":0.08900000000000001},{"name":"attackStatic","value":16}],"omit":false,"level":20,"star":5,"id":356},{"setName":"viridescentVenerer","detailName":"野花记忆的绿野","position":"flower","mainTag":{"name":"lifeStatic","value":4780},"normalTags":[{"name":"critical","value":0.07},{"name":"recharge","value":0.045},{"name":"defendStatic","value":67},{"name":"criticalDamage","value":0.054000000000000006}],"omit":false,"level":20,"star":5,"id":357},{"setName":"viridescentVenerer","detailName":"野花记忆的绿野","position":"flower","mainTag":{"name":"lifeStatic","value":4780},"normalTags":[{"name":"defendPercentage","value":0.139},{"name":"critical","value":0.062000000000000006},{"name":"recharge","value":0.11699999999999999},{"name":"attackStatic","value":29}],"omit":false,"level":20,"star":5,"id":358},{"setName":"gladiatorFinale","detailName":"角斗士的留恋","position":"flower","mainTag":{"name":"lifeStatic","value":4780},"normalTags":[{"name":"critical","value":0.109},{"name":"criticalDamage","value":0.14},{"name":"attackPercentage","value":0.057999999999999996},{"name":"elementalMastery","value":42}],"omit":true,"level":20,"star":5,"id":359},{"setName":"gladiatorFinale","detailName":"角斗士的留恋","position":"flower","mainTag":{"name":"lifeStatic","value":4780},"normalTags":[{"name":"criticalDamage","value":0.14},{"name":"attackPercentage","value":0.09300000000000001},{"name":"defendPercentage","value":0.168},{"name":"recharge","value":0.057999999999999996}],"omit":false,"level":20,"star":5,"id":360},{"setName":"blizzardStrayer","detailName":"历经风雪的思念","position":"flower","mainTag":{"name":"lifeStatic","value":4780},"normalTags":[{"name":"recharge","value":0.162},{"name":"criticalDamage","value":0.14},{"name":"attackStatic","value":29},{"name":"critical","value":0.039}],"omit":false,"level":20,"star":5,"id":361}],"feather":[{"setName":"heartOfDepth","detailName":"追忆之风","position":"feather","mainTag":{"name":"attackStatic","value":311},"normalTags":[{"name":"defendStatic","value":23},{"name":"recharge","value":0.09699999999999999},{"name":"attackPercentage","value":0.053},{"name":"criticalDamage","value":0.295}],"omit":false,"level":20,"star":5,"id":362},{"setName":"heartOfDepth","detailName":"追忆之风","position":"feather","mainTag":{"name":"attackStatic","value":311},"normalTags":[{"name":"defendStatic","value":23},{"name":"recharge","value":0.09699999999999999},{"name":"attackPercentage","value":0.053},{"name":"criticalDamage","value":0.295}],"omit":false,"level":20,"star":5,"id":363},{"setName":"crimsonWitch","detailName":"魔女常燃之羽","position":"feather","mainTag":{"name":"attackStatic","value":311},"normalTags":[{"name":"lifeStatic","value":209},{"name":"critical","value":0.066},{"name":"attackPercentage","value":0.047},{"name":"criticalDamage","value":0.326}],"omit":true,"level":20,"star":5,"id":364},{"setName":"thunderSmoother","detailName":"平雷之羽","position":"feather","mainTag":{"name":"attackStatic","value":311},"normalTags":[{"name":"attackPercentage","value":0.040999999999999995},{"name":"recharge","value":0.065},{"name":"criticalDamage","value":0.179},{"name":"critical","value":0.136}],"omit":false,"level":20,"star":5,"id":365},{"setName":"heartOfDepth","detailName":"追忆之风","position":"feather","mainTag":{"name":"attackStatic","value":311},"normalTags":[{"name":"attackPercentage","value":0.152},{"name":"recharge","value":0.09699999999999999},{"name":"critical","value":0.07},{"name":"lifePercentage","value":0.040999999999999995}],"omit":false,"level":20,"star":5,"id":366},{"setName":"noblesseOblige","detailName":"宗室之翎","position":"feather","mainTag":{"name":"attackStatic","value":311},"normalTags":[{"name":"critical","value":0.09699999999999999},{"name":"lifeStatic","value":508},{"name":"attackPercentage","value":0.09300000000000001},{"name":"elementalMastery","value":21}],"omit":false,"level":20,"star":5,"id":367},{"setName":"noblesseOblige","detailName":"宗室之翎","position":"feather","mainTag":{"name":"attackStatic","value":311},"normalTags":[{"name":"attackPercentage","value":0.09300000000000001},{"name":"defendPercentage","value":0.204},{"name":"critical","value":0.066},{"name":"criticalDamage","value":0.07}],"omit":false,"level":20,"star":5,"id":368},{"setName":"crimsonWitch","detailName":"魔女常燃之羽","position":"feather","mainTag":{"name":"attackStatic","value":311},"normalTags":[{"name":"lifeStatic","value":269},{"name":"lifePercentage","value":0.163},{"name":"criticalDamage","value":0.20199999999999999},{"name":"recharge","value":0.052000000000000005}],"omit":false,"level":20,"star":5,"id":369},{"setName":"viridescentVenerer","detailName":"猎人青翠的箭羽","position":"feather","mainTag":{"name":"attackStatic","value":311},"normalTags":[{"name":"defendPercentage","value":0.073},{"name":"criticalDamage","value":0.249},{"name":"attackPercentage","value":0.053},{"name":"critical","value":0.057999999999999996}],"omit":false,"level":20,"star":5,"id":370},{"setName":"viridescentVenerer","detailName":"猎人青翠的箭羽","position":"feather","mainTag":{"name":"attackStatic","value":311},"normalTags":[{"name":"criticalDamage","value":0.062000000000000006},{"name":"attackPercentage","value":0.047},{"name":"recharge","value":0.24},{"name":"lifeStatic","value":568}],"omit":false,"level":20,"star":5,"id":371},{"setName":"maidenBeloved","detailName":"少女飘摇的思念","position":"feather","mainTag":{"name":"attackStatic","value":311},"normalTags":[{"name":"lifePercentage","value":0.057999999999999996},{"name":"lifeStatic","value":866},{"name":"recharge","value":0.168},{"name":"elementalMastery","value":16}],"omit":false,"level":20,"star":5,"id":372},{"setName":"thunderSmoother","detailName":"平雷之羽","position":"feather","mainTag":{"name":"attackStatic","value":311},"normalTags":[{"name":"recharge","value":0.10400000000000001},{"name":"criticalDamage","value":0.062000000000000006},{"name":"attackPercentage","value":0.146},{"name":"defendStatic","value":39}],"omit":false,"level":20,"star":5,"id":373},{"setName":"blizzardStrayer","detailName":"摧冰而行的执望","position":"feather","mainTag":{"name":"attackStatic","value":311},"normalTags":[{"name":"criticalDamage","value":0.14800000000000002},{"name":"critical","value":0.10099999999999999},{"name":"lifeStatic","value":508},{"name":"attackPercentage","value":0.040999999999999995}],"omit":false,"level":20,"star":5,"id":374},{"setName":"blizzardStrayer","detailName":"摧冰而行的执望","position":"feather","mainTag":{"name":"attackStatic","value":311},"normalTags":[{"name":"attackPercentage","value":0.111},{"name":"criticalDamage","value":0.132},{"name":"elementalMastery","value":16},{"name":"defendStatic","value":63}],"omit":false,"level":20,"star":5,"id":375},{"setName":"noblesseOblige","position":"feather","detailName":"宗室之翎","mainTag":{"name":"attackStatic","value":311},"normalTags":[{"name":"defendStatic","value":39},{"name":"critical","value":0.066},{"name":"defendPercentage","value":0.051},{"name":"criticalDamage","value":0.264}],"omit":false,"star":5,"level":20,"id":376},{"setName":"viridescentVenerer","position":"feather","detailName":"猎人青翠的箭羽","mainTag":{"name":"attackStatic","value":311},"normalTags":[{"name":"lifeStatic","value":209},{"name":"criticalDamage","value":0.233},{"name":"recharge","value":0.09699999999999999},{"name":"critical","value":0.066}],"omit":false,"star":5,"level":20,"id":377}],"sand":[{"setName":"thunderingFury","detailName":"雷霆的时计","position":"sand","mainTag":{"name":"lifePercentage","value":0.466},"normalTags":[{"name":"defendPercentage","value":0.051},{"name":"critical","value":0.027000000000000003},{"name":"lifePercentage","value":0.01135},{"name":"criticalDamage","value":0.109}],"omit":false,"level":20,"star":5,"id":378},{"setName":"gladiatorFinale","detailName":"角斗士的希冀","position":"sand","mainTag":{"name":"attackPercentage","value":0.466},"normalTags":[{"name":"attackStatic","value":47},{"name":"critical","value":0.09300000000000001},{"name":"lifeStatic","value":239},{"name":"criticalDamage","value":0.109}],"omit":false,"level":20,"star":5,"id":379},{"setName":"blizzardStrayer","detailName":"冰雪故园的终期","position":"sand","mainTag":{"name":"attackPercentage","value":0.466},"normalTags":[{"name":"recharge","value":0.155},{"name":"elementalMastery","value":23},{"name":"criticalDamage","value":0.14800000000000002},{"name":"critical","value":0.10099999999999999}],"omit":false,"level":20,"star":5,"id":380},{"setName":"noblesseOblige","detailName":"宗室时计","position":"sand","mainTag":{"name":"attackPercentage","value":0.466},"normalTags":[{"name":"lifeStatic","value":209},{"name":"attackStatic","value":19},{"name":"criticalDamage","value":0.187},{"name":"recharge","value":0.19399999999999998}],"omit":false,"level":20,"star":5,"id":381},{"setName":"crimsonWitch","detailName":"魔女破灭之时","position":"sand","mainTag":{"name":"attackPercentage","value":0.466},"normalTags":[{"name":"criticalDamage","value":0.218},{"name":"recharge","value":0.11699999999999999},{"name":"critical","value":0.057999999999999996},{"name":"defendStatic","value":21}],"omit":false,"level":20,"star":5,"id":382},{"setName":"thunderingFury","detailName":"雷霆的时计","position":"sand","mainTag":{"name":"attackPercentage","value":0.466},"normalTags":[{"name":"defendPercentage","value":0.12400000000000001},{"name":"recharge","value":0.045},{"name":"critical","value":0.105},{"name":"elementalMastery","value":37}],"omit":false,"level":20,"star":5,"id":383},{"setName":"viridescentVenerer","detailName":"翠绿猎人的笃定","position":"sand","mainTag":{"name":"recharge","value":0.518},"normalTags":[{"name":"attackStatic","value":31},{"name":"attackPercentage","value":0.146},{"name":"critical","value":0.027000000000000003},{"name":"defendStatic","value":42}],"omit":false,"level":20,"star":5,"id":384},{"setName":"viridescentVenerer","detailName":"翠绿猎人的笃定","position":"sand","mainTag":{"name":"attackPercentage","value":0.466},"normalTags":[{"name":"defendStatic","value":23},{"name":"critical","value":0.09300000000000001},{"name":"lifeStatic","value":239},{"name":"recharge","value":0.162}],"omit":false,"level":20,"star":5,"id":385},{"setName":"maidenBeloved","detailName":"少女苦短的良辰","position":"sand","mainTag":{"name":"recharge","value":0.518},"normalTags":[{"name":"defendPercentage","value":0.131},{"name":"attackStatic","value":31},{"name":"lifeStatic","value":478},{"name":"lifePercentage","value":0.111}],"omit":false,"level":20,"star":5,"id":386},{"setName":"wandererTroupe","position":"sand","detailName":"终幕的时计","mainTag":{"name":"lifePercentage","value":0.466},"normalTags":[{"name":"criticalDamage","value":0.078},{"name":"attackStatic","value":33},{"name":"critical","value":0.09300000000000001},{"name":"defendStatic","value":44}],"omit":true,"star":5,"level":20,"id":387},{"setName":"wandererTroupe","position":"sand","detailName":"终幕的时计","mainTag":{"name":"recharge","value":0.518},"normalTags":[{"name":"elementalMastery","value":65},{"name":"attackStatic","value":19},{"name":"critical","value":0.113},{"name":"criticalDamage","value":0.132}],"omit":false,"star":5,"level":20,"id":388},{"setName":"wandererTroupe","position":"sand","detailName":"终幕的时计","mainTag":{"name":"recharge","value":0.518},"normalTags":[{"name":"lifePercentage","value":0.047},{"name":"defendPercentage","value":0.057999999999999996},{"name":"attackPercentage","value":0.134},{"name":"critical","value":0.10099999999999999}],"omit":false,"star":5,"level":20,"id":389}],"cup":[{"setName":"heartOfDepth","detailName":"沉波之盏","position":"cup","mainTag":{"name":"attackPercentage","value":0.466},"normalTags":[{"name":"recharge","value":0.11699999999999999},{"name":"defendPercentage","value":0.131},{"name":"lifeStatic","value":747},{"name":"criticalDamage","value":0.132}],"omit":false,"level":20,"star":5,"id":390},{"setName":"noblesseOblige","detailName":"宗室银瓮","position":"cup","mainTag":{"name":"fireBonus","value":0.466},"normalTags":[{"name":"recharge","value":0.13},{"name":"lifeStatic","value":239},{"name":"critical","value":0.09699999999999999},{"name":"attackStatic","value":49}],"omit":false,"level":20,"star":5,"id":391},{"setName":"wandererTroupe","detailName":"吟游者之壶","position":"cup","mainTag":{"name":"fireBonus","value":0.466},"normalTags":[{"name":"defendStatic","value":65},{"name":"attackPercentage","value":0.099},{"name":"critical","value":0.062000000000000006},{"name":"elementalMastery","value":37}],"omit":true,"level":20,"star":5,"id":392},{"setName":"gladiatorFinale","detailName":"角斗士的酣醉","position":"cup","mainTag":{"name":"waterBonus","value":0.466},"normalTags":[{"name":"critical","value":0.14},{"name":"recharge","value":0.13},{"name":"defendPercentage","value":0.066},{"name":"lifeStatic","value":448}],"omit":false,"level":20,"star":5,"id":393},{"setName":"maidenBeloved","detailName":"少女片刻的闲暇","position":"cup","mainTag":{"name":"lifePercentage","value":0.466},"normalTags":[{"name":"lifeStatic","value":508},{"name":"elementalMastery","value":40},{"name":"attackPercentage","value":0.17500000000000002},{"name":"critical","value":0.066}],"omit":false,"level":20,"star":5,"id":394},{"setName":"heartOfDepth","detailName":"沉波之盏","position":"cup","mainTag":{"name":"thunderBonus","value":0.466},"normalTags":[{"name":"recharge","value":0.052000000000000005},{"name":"defendStatic","value":16},{"name":"elementalMastery","value":44},{"name":"critical","value":0.14400000000000002}],"omit":false,"level":20,"star":5,"id":395},{"setName":"bloodstainedChivalry","detailName":"染血骑士之杯","position":"cup","mainTag":{"name":"fireBonus","value":0.466},"normalTags":[{"name":"critical","value":0.07},{"name":"attackStatic","value":33},{"name":"defendPercentage","value":0.19},{"name":"lifePercentage","value":0.053}],"omit":false,"level":20,"star":5,"id":396},{"setName":"noblesseOblige","detailName":"宗室银瓮","position":"cup","mainTag":{"name":"iceBonus","value":0.466},"normalTags":[{"name":"attackPercentage","value":0.192},{"name":"lifePercentage","value":0.047},{"name":"elementalMastery","value":16},{"name":"recharge","value":0.12300000000000001}],"omit":false,"level":20,"star":5,"id":397},{"setName":"noblesseOblige","detailName":"宗室银瓮","position":"cup","mainTag":{"name":"lifePercentage","value":0.466},"normalTags":[{"name":"recharge","value":0.052000000000000005},{"name":"attackPercentage","value":0.192},{"name":"lifeStatic","value":299},{"name":"critical","value":0.078}],"omit":false,"level":20,"star":5,"id":398},{"setName":"noblesseOblige","detailName":"宗室银瓮","position":"cup","mainTag":{"name":"physicalBonus","value":0.583},"normalTags":[{"name":"criticalDamage","value":0.078},{"name":"attackPercentage","value":0.198},{"name":"attackStatic","value":27},{"name":"elementalMastery","value":23}],"omit":false,"level":20,"star":5,"id":399},{"setName":"wandererTroupe","detailName":"吟游者之壶","position":"cup","mainTag":{"name":"fireBonus","value":0.466},"normalTags":[{"name":"attackStatic","value":16},{"name":"attackPercentage","value":0.040999999999999995},{"name":"criticalDamage","value":0.14},{"name":"recharge","value":0.22}],"omit":false,"level":20,"star":5,"id":400},{"setName":"wandererTroupe","detailName":"吟游者之壶","position":"cup","mainTag":{"name":"iceBonus","value":0.466},"normalTags":[{"name":"recharge","value":0.091},{"name":"critical","value":0.035},{"name":"lifePercentage","value":0.057999999999999996},{"name":"defendStatic","value":83}],"omit":false,"level":20,"star":5,"id":401},{"setName":"viridescentVenerer","detailName":"翠绿猎人的容器","position":"cup","mainTag":{"name":"windBonus","value":0.466},"normalTags":[{"name":"lifeStatic","value":807},{"name":"attackPercentage","value":0.105},{"name":"elementalMastery","value":21},{"name":"lifePercentage","value":0.105}],"omit":false,"level":20,"star":5,"id":402},{"setName":"gladiatorFinale","detailName":"角斗士的酣醉","position":"cup","mainTag":{"name":"windBonus","value":0.466},"normalTags":[{"name":"recharge","value":0.10400000000000001},{"name":"critical","value":0.066},{"name":"attackPercentage","value":0.105},{"name":"defendPercentage","value":0.11699999999999999}],"omit":false,"level":20,"star":5,"id":403},{"setName":"gladiatorFinale","detailName":"角斗士的酣醉","position":"cup","mainTag":{"name":"fireBonus","value":0.466},"normalTags":[{"name":"lifeStatic","value":807},{"name":"recharge","value":0.057999999999999996},{"name":"attackPercentage","value":0.099},{"name":"critical","value":0.07}],"omit":false,"level":20,"star":5,"id":404},{"setName":"maidenBeloved","detailName":"少女片刻的闲暇","position":"cup","mainTag":{"name":"thunderBonus","value":0.466},"normalTags":[{"name":"lifePercentage","value":0.040999999999999995},{"name":"attackPercentage","value":0.21},{"name":"critical","value":0.027000000000000003},{"name":"elementalMastery","value":37}],"omit":false,"level":20,"star":5,"id":405},{"setName":"blizzardStrayer","detailName":"遍结寒霜的傲骨","position":"cup","mainTag":{"name":"waterBonus","value":0.466},"normalTags":[{"name":"attackPercentage","value":0.09300000000000001},{"name":"lifeStatic","value":239},{"name":"recharge","value":0.11699999999999999},{"name":"criticalDamage","value":0.187}],"omit":false,"level":20,"star":5,"id":406}],"head":[{"setName":"noblesseOblige","detailName":"宗室面具","position":"head","mainTag":{"name":"criticalDamage","value":0.622},"normalTags":[{"name":"lifePercentage","value":0.09300000000000001},{"name":"critical","value":0.07},{"name":"recharge","value":0.155},{"name":"elementalMastery","value":23}],"omit":false,"level":20,"star":5,"id":407},{"setName":"noblesseOblige","detailName":"宗室面具","position":"head","mainTag":{"name":"critical","value":0.311},"normalTags":[{"name":"recharge","value":0.149},{"name":"lifeStatic","value":299},{"name":"defendPercentage","value":0.131},{"name":"criticalDamage","value":0.14}],"omit":false,"level":20,"star":5,"id":408},{"setName":"noblesseOblige","detailName":"宗室面具","position":"head","mainTag":{"name":"critical","value":0.311},"normalTags":[{"name":"defendPercentage","value":0.139},{"name":"recharge","value":0.188},{"name":"lifePercentage","value":0.099},{"name":"defendStatic","value":21}],"omit":false,"level":20,"star":5,"id":409},{"setName":"crimsonWitch","detailName":"焦灼的魔女帽","position":"head","mainTag":{"name":"critical","value":0.311},"normalTags":[{"name":"criticalDamage","value":0.11699999999999999},{"name":"lifeStatic","value":448},{"name":"attackStatic","value":37},{"name":"lifePercentage","value":0.09300000000000001}],"omit":false,"level":20,"star":5,"id":410},{"setName":"crimsonWitch","detailName":"焦灼的魔女帽","position":"head","mainTag":{"name":"criticalDamage","value":0.622},"normalTags":[{"name":"lifePercentage","value":0.040999999999999995},{"name":"defendStatic","value":19},{"name":"attackStatic","value":35},{"name":"critical","value":0.136}],"omit":true,"level":20,"star":5,"id":411},{"setName":"thunderingFury","detailName":"唤雷的头冠","position":"head","mainTag":{"name":"cureEffect","value":0.359},"normalTags":[{"name":"lifePercentage","value":0.105},{"name":"recharge","value":0.24600000000000002},{"name":"lifeStatic","value":209},{"name":"defendStatic","value":19}],"omit":false,"level":20,"star":5,"id":412},{"setName":"wandererTroupe","detailName":"指挥的礼帽","position":"head","mainTag":{"name":"criticalDamage","value":0.622},"normalTags":[{"name":"critical","value":0.09300000000000001},{"name":"defendPercentage","value":0.073},{"name":"lifePercentage","value":0.040999999999999995},{"name":"defendStatic","value":63}],"omit":false,"level":20,"star":5,"id":413},{"setName":"gladiatorFinale","detailName":"角斗士的凯旋","position":"head","mainTag":{"name":"critical","value":0.311},"normalTags":[{"name":"criticalDamage","value":0.132},{"name":"lifeStatic","value":478},{"name":"attackStatic","value":33},{"name":"defendPercentage","value":0.131}],"omit":false,"level":20,"star":5,"id":414},{"setName":"maidenBeloved","detailName":"少女易逝的芳颜","position":"head","mainTag":{"name":"critical","value":0.311},"normalTags":[{"name":"attackPercentage","value":0.053},{"name":"attackStatic","value":35},{"name":"criticalDamage","value":0.11699999999999999},{"name":"recharge","value":0.149}],"omit":false,"level":20,"star":5,"id":415},{"setName":"lavaWalker","detailName":"渡火者的智慧","position":"head","mainTag":{"name":"critical","value":0.311},"normalTags":[{"name":"criticalDamage","value":0.28800000000000003},{"name":"elementalMastery","value":40},{"name":"recharge","value":0.045},{"name":"lifeStatic","value":269}],"omit":false,"level":20,"star":5,"id":416},{"setName":"blizzardStrayer","detailName":"破冰踏雪的回音","position":"head","mainTag":{"name":"criticalDamage","value":0.622},"normalTags":[{"name":"defendPercentage","value":0.182},{"name":"attackStatic","value":31},{"name":"lifePercentage","value":0.099},{"name":"lifeStatic","value":239}],"omit":false,"level":20,"star":5,"id":417},{"setName":"blizzardStrayer","detailName":"破冰踏雪的回音","position":"head","mainTag":{"name":"critical","value":0.311},"normalTags":[{"name":"defendStatic","value":58},{"name":"elementalMastery","value":58},{"name":"recharge","value":0.052000000000000005},{"name":"attackPercentage","value":0.057999999999999996}],"omit":false,"level":20,"star":5,"id":418}]}

**Comment by wormtql** [comment]
这是个bug，正在修复，可以输小数来凑合一下，比如140输入成1.4，另外希望能够新建一个issue来反映不同的问题 😄

**Comment by qstdnx** [comment]
> 这是个bug，正在修复，可以输小数来凑合一下，比如140输入成1.4，另外希望能够新建一个issue来反映不同的问题 😄

好，我还有些其他建议，已经新开一个issue。

**Comment by qstdnx** [comment]
建议的功能已经全部实现了

**Comment by qstdnx** [comment]
剩下一个第②条不是很紧要。
