### ISSUE TITLE
另一个圣遗物自动扫描工具，可以考虑整合

### ISSUE THREAD

**Issue by ProblemFactory** [wormtql/genshin_artifact#43]
我是作者本人，工具发布在nga：https://bbs.nga.cn/read.php?tid=26425531&_ff=650
我做这个工具只是为了改善个人认为椰羊cocogoat体验不太好的地方，如果你们或是任何人想要拿走整合都欢迎（nga帖子里有github链接）。
理论上讲我这个工具扫描速度更快更自动化，不过缺点是只支持windows下的原生原神，不支持模拟器云游戏等。
如果想要整合但是有开发方面（比如AI等）的需求可以和我联系。

**Comment by wormtql** [comment]
大佬nb，我会整合的

**Comment by Hpero4** [comment]
@ProblemFactory 大佬您好, 我昨天在Github上查看了您的项目, 我想根据其大体逻辑改写为C#并整合功能以使效率提高且更契合桌面平台. 但目前C#上对Keras的支持并不完善, 如需脱离Python环境则无法直接从h5中直接读取模型, 只能在代码中先搭建模型后从h5中load_weights. 请问您是否可以提供所使用模型的源码? 非常感谢!

https://github.com/SciSharp/TensorFlow.NET/issues/583#issuecomment-745353810

**Comment by Hpero4** [comment]
@ProblemFactory 大佬您好, 我昨天在Github上看见了您的项目, 我想根据其大体逻辑改写为C#并整合功能以使效率提高且更契合桌面平台. 但目前C#上对Keras的支持并不完善, 如需脱离Python环境则无法直接从h5中直接读取模型, 只能在代码中先搭建模型后从h5中load_weights. 请问您是否可以提供所使用模型的源码? 非常感谢!

**Comment by ProblemFactory** [comment]
@Hpero4 我原模型在jupyterlab里做的，代码有点乱，我把关键部分整理出来放到这个gist里了：https://gist.github.com/ProblemFactory/401c68b341ae6338fdb8798598c60814

**Comment by Hpero4** [comment]
> @Hpero4 我原模型在jupyterlab里做的，代码有点乱，我把关键部分整理出来放到这个gist里了：https://gist.github.com/ProblemFactory/401c68b341ae6338fdb8798598c60814

好的, 非常感谢!
