### ISSUE TITLE
【胡桃-蝶引来生】目标函数缺失匣里灭辰精炼效果

### ISSUE THREAD

**Issue by cihga39871** [wormtql/genshin_artifact#51]
当选择【胡桃-蝶引来生】目标函数时，武器匝里灭辰精炼效果未计入伤害期望中：当精炼为1和5时，伤害期望相同。

由于匣里灭辰的水、火元素覆盖时增伤对胡桃影响特别大，希望能够在伤害计算中加入匣里灭辰精炼的增益。

**Comment by wormtql** [comment]
将会在下个大版本更新更详细的武器参数，comming s∞n

**Comment by wormtql** [comment]
已经可以定制化匣里龙吟效果
