### ISSUE TITLE
大佬NB！

### ISSUE THREAD

**Issue by JasCrazy** [wormtql/genshin_artifact#53]
要实现4人队伍同时配装难不难？
比如自己设置每个角色输出比例，然后配装使得总输出最大化。可以使得一个配队能够优化配装。
因为像胡桃行秋搭配，其实两个都有输出，如果胡桃带好圣遗物，可能导致行秋纯粹挂水。而如果能达到减少一定胡桃输出，行秋提升的输出能弥补的配装其实更好是吧。
大佬是否愿意为此挠破头皮(✿◕‿◕✿)

**Comment by wormtql** [comment]
这个是非常难的，至少要做最优解是很难的。但是可能可以通过某种贪心法得出较优解，或者再高级一点可以上一些nb的优化算法，但是这就涉及我的只是盲区了🤣，多人的配装感觉做好了都能发论文了
