### ISSUE TITLE
圣遗物导出器（artifacts exporter）

### ISSUE THREAD

**Issue by xyfeng298** [wormtql/genshin_artifact#6]
目前配装工具很好用，但是手动输入圣遗物门槛有点高，在没有工具能导出原神圣遗物的情况下，是否可以参考下泥潭里圣遗物评分工具，按图识别来添加每一个圣遗物，这样子也不用痛苦一个个输入圣遗物了。

**Comment by xyfeng298** [comment]
刚在泥潭发现了有位潭友针对作者的工具开发了圣遗物导出工具。
https://bbs.nga.cn/read.php?tid=25595872
作者看看，如果合适的话，弄到简介吧。

**Comment by wormtql** [comment]
感谢支持！ 😄 我也正头疼圣遗物导出的办法

**Comment by yinxin630** [comment]
手动一个个输入可太麻烦了, 加个 OCR 识别的功能吧, 游戏里截图, 网页上粘贴图片识别
可莉特调那个只能选择图片不能直接粘贴, 而且识别结果经常缺百分号, 可以加些逻辑对识别结果做些简单修复, 还不对的就手动改一下就好了

另外, 作者如果没时间我可以试试看

**Comment by yinxin630** [comment]
![image](https://user-images.githubusercontent.com/6939365/112121633-69ea9c00-8bfa-11eb-991b-3333021164bc.png)

**Comment by wormtql** [comment]
> 手动一个个输入可太麻烦了, 加个 OCR 识别的功能吧, 游戏里截图, 网页上粘贴图片识别
> 可莉特调那个只能选择图片不能直接粘贴, 而且识别结果经常有错误, 可以加些逻辑对识别结果中太离谱的数据做些简单修复, 还不对的就手动改一下就好了
> 
> 另外, 作者如果没时间我可以试试看

主要是百度API不付钱的话有次数限制，最好是能够做成不调用其他API的方式识图的，如果大佬愿意的话，可以帮忙写😄

**Comment by Mr-Quin** [comment]
是否可以考虑 [tesseract.js](https://github.com/naptha/tesseract.js#tesseractjs) 前端运行ocr
根据demo来看如果分辨率够高还是可以的，支持识别中文
参考[这个库](https://github.com/frzyc/genshin-optimizer)

**Comment by wormtql** [comment]
我试过tesseract，用的是圣遗物的截图，效果不好（不是正确率的问题，是根本几乎无法识别）

**Comment by wormtql** [comment]
就像这样
![image](https://user-images.githubusercontent.com/42363449/112275891-0eccae00-8cbb-11eb-885f-666d41daa81a.png)
![image](https://user-images.githubusercontent.com/42363449/112275924-1724e900-8cbb-11eb-81b9-72ca23c8c28b.png)

**Comment by Mr-Quin** [comment]
这样啊 
那tensorflow.js的可行性怎么样？搞一个原神ocr模型

**Comment by wormtql** [comment]
或许是可行的，只是我并不会cv方面的内容，只能期待别的大佬来搞了

**Comment by Mr-Quin** [comment]
我用tesseract测试了半天 似乎还是有搞头的
![image](https://user-images.githubusercontent.com/8700123/112398623-d41a4400-8cc1-11eb-8430-c906e2e00ce5.png)
![image](https://user-images.githubusercontent.com/8700123/112398655-e300f680-8cc1-11eb-823f-1f8fb601776a.png)

沿用之前提到的国外作者的代码，先对图片进行处理，再进行识别
![image](https://user-images.githubusercontent.com/8700123/112398791-222f4780-8cc2-11eb-9bb5-2c286edf3cc4.png)
最后对结果进行模糊比对（作者用的汉明距离） 猜出一个最合适的 因为每个词条都是有固定值的，还可以用子集和对数值进行纠错

虽然比直接调用api复杂了不少，但也是个方法 大概

然后我正在用原神的字体训练tesseract，还不知道结果会不会更好

**Comment by wormtql** [comment]
感谢大佬，如果可以的话，我觉得可以做成npm包的形式，把ocr的功能发布了

**Comment by Mr-Quin** [comment]
https://github.com/Mr-Quin/genshin-ocr/tree/main
先整了一个网页demo 大佬也可以测试一下
