### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by qstdnx** [wormtql/genshin_artifact#64]
①重新配装，读取预设配装，计算结果不会自动回到冠军，经常某个角色用了亚军季军，读取后忘了调回冠军配了几个才发现。
②希望能导出套装
③希望保存预设能同时保存套装禁用
④希望能增加全局buff缺少角色，罗莎莉亚万叶砂糖北斗岩主猫猫阿贝多之类的，虽然都可以自定义，但是有的要自己算的。

**Comment by wormtql** [comment]
3. 这样就没法导出预设给别人用，所以不会保存套装禁用

**Comment by qstdnx** [comment]
> 1. 这样就没法导出预设给别人用，所以不会保存套装禁用

恩，我只是建议，每次重新点一下禁用也不是很麻烦，就是有的时候老年痴呆发作会忘记，配完发现不对劲才回过头去改。
