### ISSUE TITLE
i18n support?

### ISSUE THREAD

**Issue by rikai** [wormtql/genshin_artifact#69]
Hello, have you ever considered adding i18n support?

This would allow others to contribute translations for other languages to allow this awesome tool to be used by many more people!

I humbly request you consider this. :)

**Comment by wormtql** [comment]
I really want to add i18n support, but for some architectural reasons it's not very simple to do this(because I was not considering i18n at the beginning of this project), but I will try adding i18n anyway. and thanks for your suggestion!

**Comment by wormtql** [comment]
now i18n is supported
