### ISSUE TITLE
魈的攻击力数值计算有误

### ISSUE THREAD

**Issue by LilLaian** [wormtql/genshin_artifact#7]
魈的攻击力数值计算有误，计算值3022，实际24xx，别的数值无误

**Comment by wormtql** [comment]
能说一下详细的配置吗，圣遗物json字符串，角色等级、武器、武器等级、目标函数等。圣遗物导出字符串如果太长发我qq也行

**Comment by LilLaian** [comment]
dbp是我的问题，输入的时候把一个生命值数值词条写成攻击力数值了qwq
