### ISSUE TITLE
Artifacts Planning BUG

### ISSUE THREAD

**Issue by LazyShiro** [wormtql/genshin_artifact#72]
Artifacts Planning进行计算时，如果勾选过滤圣遗物组，此时圣遗物组为空，console报错Cannot read property 'ids' of undefined

发现此bug的契机是自定义了一套圣遗物组，然后进行Artifacts Planning计算时，勾选了过滤圣遗物组，然后想着重置算一下别的角色，就把圣遗物组删掉了，但是Artifacts Planning还保持着过滤圣遗物组的勾选状态，导致了bug

**Comment by wormtql** [comment]
已经修复，https://github.com/wormtql/genshin_artifact/commit/d95ea451121773633567f74b5c78f9adabbdceac
