### ISSUE TITLE
safari浏览器“选择角色”下拉框显示空白 没有内容

### ISSUE THREAD

**Issue by moesnow** [wormtql/genshin_artifact#76]
Mac和iPad都试了，全部是这样，切chrome就没问题
![截屏2021-10-10 下午10.26.34.png](https://i.loli.net/2021/10/10/37ODEfSCIPUcxnR.png)

**Comment by ernestyao** [comment]
是的，一样情况，Apple Silicon的本子。同时，在上一代铺子的最新版也这样（依稀记得是去年底开始消失的）
