### ISSUE TITLE
能不能添加一个自定义技能等级的选项？

### ISSUE THREAD

**Issue by AizawaHikaru233** [wormtql/genshin_artifact#9]
对于女仆来说，不止满命会影响圣遗物的选择，技能等级也会影响，非满命女仆大招等级较高的情况下，也会影响圣遗物攻击与防御属性的取舍，我自己用Excel做的简易计算器计算我5命女仆的伤害期望，攻击沙漏+暴击头最高，但是该网页内计算非满命女仆，却得出了攻击沙+攻击头的结果。

**Comment by AizawaHikaru233** [comment]
面板攻击 | 面板防御 | 基础攻击 | 基础防御 | 大招等级 | 暴击     | 爆伤     | 白影剑精炼等级 | 伤害期望     |  
1484        | 1638        | 701          | 799         | 11            | 71.90% | 97.40% | 5                        | 5707.64703 | 
1145        | 2103        | 701          | 799         | 11            | 68.80% | 97.40% | 5                        | 5630.34036 | 
1809        | 1600        | 701          | 799         | 11            | 47.70% | 106.70% | 5                      | 5512.15963 |  
第三项为占卜铺计算出来的配装数据

**Comment by wormtql** [comment]
这个以后肯定会加上的，只是要加技能等级要录入很多数据，所以还是应该比较慢的，但是一定会加上的

**Comment by wormtql** [comment]
已经支持自定义技能等级了
