### ISSUE TITLE
art planner状态的后续问题

### ISSUE THREAD

**Issue by sidious-82** [wormtql/genshin_artifact#95]
修复https://github.com/wormtql/genshin_artifact/issues/92之后

融化的冰变成了水
![image](https://user-images.githubusercontent.com/95687554/146320926-37025cde-e221-453c-a685-7aebbffc2ff1.png)

减抗以及上面的融化好像还是没法被存储

复现方式为存储之后，关闭当前网页再重新打开，读取之前的preset

另外新发现的一个状态问题试，圣遗物参数的华冠四件套效果比例状态无法被存储
![image](https://user-images.githubusercontent.com/95687554/146321206-cc389275-0a7e-48a0-ba58-1eee620517bb.png)

每次重新打开网站读取之后都会变回0

**Comment by wormtql** [comment]
没能复现这个问题，试试把原先的预设删了，再重新来一遍
